CFLAGS = -std=c11 -pedantic -Wall -Wextra -c -o
OBJ = main.o InterpreterState.o Lexemes.o Analyzer.o TinyFunctions.o TinyVariables.o
EXE = InterpreterTinyBasic

all: $(EXE)
$(EXE) : $(OBJ)
	gcc -o $(EXE) $(OBJ)

main.o : main.c
	gcc $(CFLAGS) main.o main.c

InterpreterState.o : InterpreterState.c
	gcc $(CFLAGS) InterpreterState.o InterpreterState.c

Lexemes.o : Lexemes.c
	gcc $(CFLAGS) Lexemes.o Lexemes.c

Analyzer.o : Analyzer.c
	gcc $(CFLAGS) Analyzer.o Analyzer.c

TinyFunctions.o : TinyFunctions.c
	gcc $(CFLAGS) TinyFunctions.o TinyFunctions.c

TinyVariables.o : TinyVariables.c
	gcc $(CFLAGS) TinyVariables.o TinyVariables.c
